<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
	<!-- Generated by OpenX 2.8.1 -->
<script type='text/javascript' src='http://d1.openx.org/spcjs.php?id=13046'></script>
	<?php 
	include($_SERVER['DOCUMENT_ROOT'].'/includes/headcommon.php');

	
	?>
	<meta http-equiv="description" content="Comparte fácilmente la ruta hacia el destino que tú elijas" />
        <title><?php include($_SERVER['DOCUMENT_ROOT'].'/includes/title.php'); ?></title>
		       <link href="estilos.css" rel="stylesheet" type="text/css" />



	
	</head>
<body>
<!--/* OpenX Interstitial or Floating DHTML Tag v2.8.1 */-->

<!--/*
  * This tag has been generated for use on a non-SSL page. If this tag
  * is to be placed on an SSL page, change the
  *   'http://d1.openx.org/...'
  * to
  *   'https://d1.openx.org/...'
  *
  *------------------------------------------------------------*
  * This interstitial invocation code requires the images from:
  * /www/images/layerstyles/simple/...
  * To be accessible via: http(s)://c3.openx.org/layerstyles/simple/...
  *------------------------------------------------------------*
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var ox_u = 'http://d1.openx.org/al.php?zoneid=49130&layerstyle=simple&align=center&valign=middle&padding=2&closetime=5&padding=2&shifth=0&shiftv=0&closebutton=t&backcolor=FFFFFF&noborder=t';
   if (document.context) ox_u += '&context=' + escape(document.context);
   document.write("<scr"+"ipt type='text/javascript' src='" + ox_u + "'></scr"+"ipt>");
//]]>--></script>


<table width="950" border="0" align="center" cellpadding="10" cellspacing="10">
  <tr>
    <td colspan="2" align="center"><?php include($_SERVER['DOCUMENT_ROOT'].'/includes/top.php'); ?></td>
  </tr>
  <tr>
    <td align="center" height="5"></td>
    <td align="center"></td>
  </tr>
  <tr>
    <td width="50%" align="center" class="celdahome"><p><a href="crea-una-direccion.php" class="linkhome">Crea una nueva direcci&oacute;n<br>
    y comp&aacute;rtela</a> <br><font color="#999999">(www.comoseva.com/mi-direccion) </font></p></td>
    <td width="50%" align="center" class="celdahome"><p><a href="ruta.php" class="linkhome">Encuentra una ruta<br>
    entre dos puntos</a> <br>
    <font color="#999999">(Planea bien tu pr&oacute;ximo viaje) </font></p></td>
  </tr>
  <tr>
    <td colspan="2" align="center"><p>&nbsp;</p>
    <p><a href="ya-creadas.php"><font size="2">Lista de direcciones ya creadas</font></a><font size="2"><br>
        <a href="logos-para-tu-web.php">Logos para usar en tu web</a> </font></p>    </td>
  </tr>
  <tr>
    <td colspan="2" align="center"><?
include($_SERVER['DOCUMENT_ROOT'].'/includes/footer.php');

include($_SERVER['DOCUMENT_ROOT'].'/includes/tagga.php'); ?></td>
  </tr>
</table>
  
</body>
</html>
